name: Blender Build (NPR Prototype)

# 手动触发
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ 拉取源码
      - uses: actions/checkout@v3
        with:
          repository: bb-yi/blender   # 指定仓库
          ref: npr-prototype           # 指定分支

      # 2️⃣ 安装依赖
      - name: Install dependencies
        run: |
          choco install cmake ninja python -y
          SET PATH=%PATH%;C:\Program Files\CMake\bin

      # 3️⃣ 创建 Ninja 构建目录并配置
      - name: Configure Blender build
        run: |
          mkdir build_ninja
          cd build_ninja
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_LITE=ON -DUSE_CCACHE=ON ..

      # 4️⃣ 编译 Blender
      - name: Build Blender
        run: |
          cd build_ninja
          ninja blender

      # 5️⃣ 上传构建产物
      - name: Upload Blender binary
        uses: actions/upload-artifact@v3
        with:
          name: blender-build
          path: build_ninja\bin\Release\blender.exe
